# This is a rather trivial Makefile, serving mostly as a reminder that if you
# want to produce doxygen documentation, all you really need to do is invoke
# `doxygen` and pass in the configuration file

all:
	doxygen remus_doxygen.cfg

clean:
	rm -rf dist
